name: "llm-cli Flow Verification (Windows)"
description: "Verify the llm-cli flow on Windows"

runs:
  using: "composite"
  steps:
    - name: Test llama llm-cli
      shell: pwsh
      run: |
        llm-cli.ps1 -t $THREAD_NUM -n 256 -x llama -m $LLAMA_INT4_CKPT_PATH -p 'Once upon a time,'

    - name: Test gptneox llm-cli
      shell: pwsh
      run: |
        llm-cli.ps1 -t $THREAD_NUM -n 256 -x gptneox -m $GPTNEOX_INT4_CKPT_PATH -p 'Once upon a time,'

    - name: Test bloom llm-cli
      shell: pwsh
      run: |
        llm-cli.ps1 -t $THREAD_NUM -n 256 -x bloom -m $BLOOM_INT4_CKPT_PATH -p 'Once upon a time,'

    - name: Test starcoder llm-cli
      shell: pwsh
      run: |
        llm-cli.ps1 -t $THREAD_NUM -n 256 -x starcoder -m $STARCODER_INT4_CKPT_PATH -p 'def check_odd('

    # - name: Test chatglm llm-cli
    #   shell: pwsh
    #   run: |
    #     llm-cli.ps1 -t $THREAD_NUM -n 256 -x chatglm -m $CHATGLM_INT4_CKPT_PATH -p '你好'
